### ISSUE TITLE
Instances of java.util.Random are not cryptographically secure

### ISSUE THREAD

**Issue by dhcgn** [gematik/ref-idp-server#1]
Instances of java.util.Random are not cryptographically secure. Consider instead using SecureRandom to get a cryptographically secure pseudo-random number generator for use by security-sensitive applications.

https://github.com/gematik/ref-idp-server/blob/694ebd6a0996f4debb5b955b77a464fe7ae38cec/idp-crypto/src/main/java/de/gematik/idp/crypto/Nonce.java#L20

**Comment by Arkinator** [comment]
Thanks for the headsup.
Currently none of the random sources in the server are hardened. This is deliberate and will be addressed in a later release.

**Comment by RStaeber** [comment]
java.util.Random is no longer part of the project.

**Comment by RStaeber** [comment]
java.util.Random is no longer part of the project.
