### ISSUE TITLE
Ability to add a custom clientId for authentication against the Authenticator application

### ISSUE THREAD

**Issue by dotWee** [gematik/ref-idp-server#10]
I'm aware of the ability to add the necessary ti-messenger related scopes to the idp-server's `application.yml`, yet I can't find any documentation/details on how to add a `clientId` to the idp-server to authenticate for.  

Digging through the source code and debugging the incoming requests (_like following the clientId lookup_) did not help <small>(but maybe I missed something?)</small>.  

Is there a way to add a custom clientId for local development?  

(Maybe @RStaeber can point me in the right direction)

**Comment by RStaeber** [comment]
Hi Lukas,
the idp-server's application.yaml (https://github.com/gematik/ref-idp-server/blob/master/idp-server/src/main/resources/application.yml) has a section "registeredClient".
Here you can add clients by adding an entry of the form:
<clientId>:
   redirecUri: <redirectUri>
   returnSsoToken: true or false

Just replace <clientId> and <redirectUri> with your own client_id and redirect_uri and everything should work.
