### ISSUE TITLE
Issue with building Dockerimage

### ISSUE THREAD

**Issue by CWeykopf** [gematik/ref-idp-server#3]
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.34.1:build (default) on project idp-server: Configured Dockerfile "/Users/chris/Entwicklung/DEOS/E-Rezept/ref-idp-server/idp-server/target/tmpdocker/Dockerfile" (resolved to "/Users/chris/Entwicklung/DEOS/E-Rezept/ref-idp-server/idp-server/target/tmpdocker/Dockerfile") doesn't exist -> [Help 1]

macOS 11.6
openjdk 11.0.2
Apache Maven 3.8.2
Docker version 20.10.8, build 3967b7d

Any hints?

**Comment by Kgessner** [comment]
I'm very much surprised that Arkinator has a working docker compose part on his maschine (linux?)
there are necessary files missing on github like
idp-server/buildDockerImage.sh
idp-server/deleteDockerImage.sh
**idp-server/Dockerfile**
at least the dockerfile would be usefull ;-)

**Comment by tiki-sup-daniel** [comment]
I see the same errors, the files are just missing in the repo - can you maybe add the Dockerfile @Arkinator?
According to the `idp-server/pom.xml - maven-resource-plugin` they should be located in `/src/main/docker`.

**Comment by DaMo86** [comment]
I see the same errors, the files are just missing in the repo - can you maybe add the Dockerfile @Arkinator?
According to the idp-server/pom.xml - maven-resource-plugin they should be located in /src/main/docker.

**Comment by Arkinator** [comment]
The file was stripped during the release to github due to internal information being present. I'm sorry about that. I'm no longer with the team but I'll adress the issue.

The dockerfile itself is really nothing special, the following might be a good starting point:

```
FROM adoptopenjdk/maven-openjdk11:latest
RUN mkdir /app
COPY /target/idp-server*.jar /app/idp-server.jar
WORKDIR /app
HEALTHCHECK CMD curl --fail http://localhost:8080/actuator/health | grep UP || exit 1
CMD ["java", "-jar", "idp-server.jar"]
```

**Comment by DaMo86** [comment]
Thank you for the fast reply!

I was able to build the system with a slight change (the .jar is already copied to the tmpDocker folder, so no `target` necessary):
```COPY ./idp-server*.jar /app/idp-server.jar```

I created 5 similiar Dockerfiles, which copying the corresponding artifact (e.g. idp-sektoral*.jar, idp-server*.jar, ...):
![grafik](https://user-images.githubusercontent.com/190957/180395284-481de4f0-6c9c-43d7-b448-4b39e6ddd61d.png)

**Comment by DaMo86** [comment]
I also found the overall problem: looks like everything about Docker is ignored in `.gitignore`

**Comment by RStaeber** [comment]
There is an image available on docker hub as well:
https://hub.docker.com/r/gematik1/idp-server/
