### ISSUE TITLE
Provide a running local docker-compose setup

### ISSUE THREAD

**Issue by DaMo86** [gematik/ref-idp-server#4]
According to the `.gitignore`, it looks like there is already a running docker-compose setup given in your internal environment.

It would be great if there is a way to share this setup and allow a simple and easy local development and testing environment for everyone.

**Comment by florianschiller** [comment]
I'm also interested in a docker-compose file. It's a pity that this is missing so far.

**Comment by dd52** [comment]
+1

**Comment by RStaeber** [comment]
You are right. We will provide docker support in a few days.

**Comment by DaMo86** [comment]
Any news here @RStaeber ?

**Comment by RStaeber** [comment]
Sorry, I thought it was done. All files compose* have been ignored. My fault.
Little fix release is just in progress and will come today.

**Comment by manuelbaumann-oviva** [comment]
Hi @RStaeber 
The provided docker compose file lacks read access to the Google Artefact Registry.

`Pulling idpserver (eu.gcr.io/gematik-all-infra-prod/idp/idp-server:21.0.1)...
ERROR: Head "https://eu.gcr.io/v2/gematik-all-infra-prod/idp/idp-server/manifests/21.0.1": denied: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/gematik-all-infra-prod/locations/europe/repositories/eu.gcr.io" (or it may not exist)`

**Comment by RStaeber** [comment]
Yes, there is no image on docker hub this time. You have to build (as you wrote already) before using the compose file.
I created an internal ticket to provide the image on docker hub. Stay tuned :-)

**Comment by RStaeber** [comment]
There is a published [docker image](https://hub.docker.com/r/gematik1/idp-server).
