### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by simse07** [gematik/ref-idp-server#6]
Hello,
we are going to use the central IDP to authenticate doctors based on their HBA and SMCB cards.
As a preliminary work, we look at the reference implementation of the IDP and have a few questions and comments about it:

1. Can you please provide the [.puml files](https://github.com/gematik/ref-idp-server/tree/master/doc) as pictures?
2. Is there a communication with the Authenticator App or is this omitted?
From the workflow-base.puml it looks like that the IDP is called from the Authenticator app and not directly from our application. Or is the phrase Authenticator in the diagram misleading.
If not, how can we start the process via the Authenticator?
4. What is the reason behind the regex for the [state query parameter](https://github.com/gematik/ref-idp-server/blob/master/idp-server/src/main/java/de/gematik/idp/server/controllers/IdpController.java#L99)?
E.g. Keycloak passes _CAJ6m-Dqt01-WTPyBIY0JwIW_DlxOaAhRof9wuH-UPs.zB7aqDc2-2U.account-console_ which doesn't match the regex.
5. In your documentation Java 11 is mentioned, but Java 17 is mandatory since v21.0.0

Best regards

**Comment by spilikin** [comment]
Hi,

besides all your other questions, if you would like a more elaborative Examples on how to implement the Authentication, look hier:

https://github.com/gematik/api-vzd/blob/feature/sample-fhir-search/samples/directory-samples-java/auth-samples/src/test/java/de/gematik/directory/samples/ownersignin/OwnerSignInSample.java

https://github.com/gematik/api-vzd/blob/feature/sample-fhir-search/samples/directory-samples-python/directory_samples/search_api_idp.py

**Comment by simse07** [comment]
Thank you @spilikin for the additional information. 

2. I also found out how to call the Authenticator, passing the _challenge_path_ to the ref-idp server.
It would be nice to have a working example for this documented.

**Comment by RStaeber** [comment]
...
>     1. Can you please provide the [.puml files](https://github.com/gematik/ref-idp-server/tree/master/doc) as pictures?
> 
>     2. Is there a communication with the Authenticator App or is this omitted?
>        From the workflow-base.puml it looks like that the IDP is called from the Authenticator app and not directly from our application. Or is the phrase Authenticator in the diagram misleading.
>        If not, how can we start the process via the Authenticator?
> 
>     3. What is the reason behind the regex for the [state query parameter](https://github.com/gematik/ref-idp-server/blob/master/idp-server/src/main/java/de/gematik/idp/server/controllers/IdpController.java#L99)?
>        E.g. Keycloak passes _CAJ6m-Dqt01-WTPyBIY0JwIW_DlxOaAhRof9wuH-UPs.zB7aqDc2-2U.account-console_ which doesn't match the regex.
> 
>     4. In your documentation Java 11 is mentioned, but Java 17 is mandatory since v21.0.0
...

Hello,

1. These puml were just used for development and not updated. Anyway, you can use an online viewer like this:
https://sujoyu.github.io/plantuml-previewer/
2. Communication with the authenticator app is omitted as our goal was only to provide a reference implementation for the server. But the gematik authenticator team has the necessary infos on this topic.
3. The state parameter may have at most 32 base64url characters.
4. You are right, there is a statement "OpenJDK 11"  in idp-testsuite/README.md. Thank you for this finding, we will fix this.

Regards, Robert
